import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

fs.mkdirSync('artifacts', { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' });
await page.evaluate(() => document.fonts.ready);
await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
assert.equal(await page.locator('h1').innerText(), 'A little care.\nA lifetime\nof smiles.');
assert.equal(await page.locator('img').evaluateAll(imgs => imgs.filter(i => !i.complete || i.naturalWidth === 0).length), 0, 'All images load');
await page.getByRole('button', { name: 'Explore Braces & aligners' }).click();
await page.getByRole('dialog').waitFor();
assert.match(await page.getByRole('dialog').innerText(), /Dr. Rishabh Jain/);
await page.getByRole('button', { name: 'Plan a consultation' }).click();
assert.equal(await page.getByLabel('What can we help with?').inputValue(), 'Braces & aligners');
await page.getByLabel('Your name').fill('Demo Visitor');
await page.getByLabel('Phone number').fill('abcdefghij');
assert.ok(await page.getByLabel('Phone number').evaluate(el => !el.validity.valid), 'Invalid phone rejected');
await page.getByLabel('Phone number').fill('9999999999');
assert.ok(await page.getByLabel('Phone number').evaluate(el => el.validity.valid), 'Valid phone accepted');
const nextSunday = new Date();
nextSunday.setDate(nextSunday.getDate() + (7 - nextSunday.getDay() || 7));
const sundayDate = `${nextSunday.getFullYear()}-${String(nextSunday.getMonth()+1).padStart(2,'0')}-${String(nextSunday.getDate()).padStart(2,'0')}`;
await page.getByLabel('Preferred date').fill(sundayDate);
assert.equal(await page.getByLabel('Preferred time').locator('option').count(), 2, 'Sunday hours offered');
await page.getByRole('button', { name: 'Review appointment request' }).click();
assert.match(await page.getByRole('dialog').innerText(), /Awaiting confirmation/);
assert.equal(await page.getByRole('link', { name: 'Call to confirm your visit' }).getAttribute('href'), 'tel:+918349476799');
await page.getByRole('button', { name: 'Edit details' }).click();
assert.equal(await page.getByLabel('Your name').inputValue(), 'Demo Visitor', 'Editing preserves the name');
assert.equal(await page.getByLabel('Phone number').inputValue(), '9999999999', 'Editing preserves the phone');
assert.equal(await page.getByLabel('What can we help with?').inputValue(), 'Braces & aligners', 'Editing preserves selected care');
await page.getByRole('button', { name: 'Review appointment request' }).click();
await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
await page.getByRole('button', { name: 'Copy request' }).click();
await page.getByRole('button', { name: 'Copied', exact: true }).waitFor();
assert.match(await page.evaluate(() => navigator.clipboard.readText()), /Demo Visitor/);
await page.screenshot({ path: 'artifacts/appointment.png' });
await page.keyboard.press('Escape');
assert.equal(await page.getByRole('dialog').count(), 0);
await page.getByRole('button', { name: 'View Space to feel at ease' }).click();
assert.match(await page.getByRole('dialog').innerText(), /1 \/ 5/);
await page.keyboard.press('ArrowRight');
assert.match(await page.getByRole('dialog').innerText(), /2 \/ 5/);
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'What are your opening hours?' }).click();
assert.equal(await page.getByRole('button', { name: 'What are your opening hours?' }).getAttribute('aria-expanded'), 'true');
assert.match(await page.locator('#faq-3').innerText(), /Sunday/);
const firstReview = await page.locator('.review-card').first().innerText();
await page.getByRole('button', { name: 'Next patient story' }).click();
assert.notEqual(await page.locator('.review-card').first().innerText(), firstReview);
for (const width of [1440, 1024, 768, 390, 320]) {
  await page.setViewportSize({ width, height: 900 });
  await page.evaluate(() => window.scrollTo(0, 0));
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No overflow at ${width}px`);
  if (width === 390) {
    await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
    await page.getByRole('button', { name: 'Open menu' }).click();
    assert.equal(await page.getByRole('button', { name: 'Close menu' }).getAttribute('aria-expanded'), 'true');
    await page.getByRole('navigation').getByRole('link', { name: 'Our doctors' }).click();
    assert.equal(await page.getByRole('button', { name: 'Open menu' }).getAttribute('aria-expanded'), 'false');
    await page.getByRole('button', { name: 'Book an appointment', exact: true }).first().click();
    await page.getByRole('button', { name: 'Review appointment request' }).click();
    assert.ok(await page.getByLabel('Your name').evaluate(el => !el.validity.valid), 'Required form fields validated');
    await page.keyboard.press('Escape');
  }
}
assert.deepEqual(errors, [], 'No JavaScript runtime errors');
await page.setViewportSize({ width: 1440, height: 1000 });
await page.locator('#visit').scrollIntoViewIfNeeded();
await page.waitForTimeout(2000);
await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
await page.screenshot({ path: 'artifacts/hero.png' });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
await page.screenshot({ path: 'artifacts/mobile-hero.png' });
await browser.close();
console.log('PASS: desktop/mobile layouts, 5 responsive widths, image loading, service details, appointment planning and validation, Sunday hours, gallery keyboard navigation, FAQ, reviews, mobile menu, and no runtime errors.');
